name: Create "SR2MDL ZIP"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkou@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'SR2MDL.zip'
        exclusions: '*.git* .gitignore .gitmodules readme.md /SR2Tools/Documentation /SR2Tools/GUIbackend SR2Tools/Changelog.txt SR2Tools/GUI_Run.py SR2Tools/README.md SR2Tools/SARCextractor.py SR2Tools/batchBINDATAconversion.py SR2Tools/bin_files_tool.py SR2Tools/bmp_handler.py SR2Tools/bmp_png_conversion.py SR2Tools/color_conversion.py SR2Tools/exe_dll_patcher.py SR2Tools/texture_classes.py SR2Tools/texture_tool.py SR2Tools/unyakuza.py'
